# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf988138a7e7bb3ce11ee3c2aa0d1fc3473a4ae3ce3f8adfd098fc60288415cdbdb75cca82d3a630f218da11826485513dcc966900ce7220c906c06542d34fc9

test:
  secret_key_base: 8c54cceded3779bbcff6ca99e0b9b58a484bb83ddb80a1d59fedbbbfb39c332aa4bfe192fd33b6b04a96dfcc7fcb3f802dd3f01fc42817ab6100afed7c59f5c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
